### ISSUE TITLE
Simplify environment detection (development vs. production)

### ISSUE THREAD

**Issue by iakunin** [Mitrichius/hugo-theme-anubis#101]
For now, the production build can be obtained using:
* either `HUGO_ENV=production` environment variable 
* or editing the config file (putting `env: production` to `params` section of config).

`Hugo` documentation states that:
> Default environments are development with `hugo server` and production with `hugo`. ([source](https://gohugo.io/getting-started/configuration/))

We can use this feature to simplify the production build process. Running just a `hugo` command is enough for that.

Talking about implementation details we can use a convenient hugo-function `hugo.IsProduction` ([https://github.com/gohugoio/hugo/issues/6873](gh-issue), [documentation](https://gohugo.io/functions/hugo/)) to detect if there is a production build.

Here is my pull request for that: https://github.com/Mitrichius/hugo-theme-anubis/pull/102.

**Comment by Mitrichius** [comment]
Tested and merged, thanks!

**Comment by iakunin** [comment]
Thank you for such rapid feedback! It's a pleasure to contribute to such kind of a project :)
