### ISSUE TITLE
Inline Code Highlight

### ISSUE THREAD

**Issue by mind-rot** [Mitrichius/hugo-theme-anubis#117]
Having trouble making inline code to be highlighted.
After adding markdown syntax for inline code, like this: `some_code`, resulted in:
```
<code>some_code</code>
```
which have background color same as main theme and is indistinguishable as a result.

Using default setup, nothing fancy added in config file.

**Comment by Mitrichius** [comment]
I made <code> similar to <pre> (fg/bg colors). Is it ok now?

**Comment by mind-rot** [comment]
Yes, that looks great. Thanks
