### ISSUE TITLE
Feature Request: Copy Markdown Code

### ISSUE THREAD

**Issue by elibroftw** [Mitrichius/hugo-theme-anubis#122]
It would be great if readers can copy code.
```
one of these
```

**Comment by elibroftw** [comment]
![image](https://user-images.githubusercontent.com/21298211/149354953-6390367d-e459-467d-b31b-8802adea4d26.png)
Thanks, it is good enough.
Next up will be better syntax high lightning, but I don't have time right now to do that.

**Comment by Mitrichius** [comment]
@elibroftw 
Syntax highlight should work with shortcode or specific markdown, see examples here
https://github.com/Mitrichius/hugo-theme-anubis/blob/master/exampleSite/content/post/markdown-syntax.md
https://hugo-theme-anubis.netlify.app/post/markdown-syntax/

Please don't close the issue, I think it should be available out of the box with correct i18n or icons

**Comment by elibroftw** [comment]
I mean syntax highlighting works, it's just not that good. It's on my todo to create a better highlight theme.

**Comment by Mitrichius** [comment]
Done!
