### ISSUE TITLE
Feature Request: Header Permalinks

### ISSUE THREAD

**Issue by elibroftw** [Mitrichius/hugo-theme-anubis#123]
For example in my post here https://elibroftw.github.io/posts/hugo_tutorial/,
it would be great if each heading also had the permalink beside it as seen https://gohugo.io/getting-started/quick-start/.
I'm not sure if it's a theme or hugo issue, but I'll leave it here for now.

I know this is the third issue I've created, but believe me when I say that your theme is the best dark theme for Hugo blogs. It's so good, that I didn't want to create a theme from scratch myself. So I applaud you for that.

**Comment by elibroftw** [comment]
Actually, can you make it like GitHub does it with the premalink icon on the left of each header and not the right?

**Comment by Mitrichius** [comment]
Please check https://deploy-preview-129--hugo-theme-anubis.netlify.app/post/markdown-syntax/
Is that solution ok?

**Comment by elibroftw** [comment]
Yeah this is pretty good. I'm not so sure about the "#" symbol instead of a link symbol. It's up to you whether to stick to "#" instead of the usual link used by GitHub and Hugo.
![image](https://user-images.githubusercontent.com/21298211/147502051-1a017a34-54e0-49e1-b7ba-d1d8801ef826.png)

**Comment by Mitrichius** [comment]
Changed icon

**Comment by Mitrichius** [comment]
Tried to change to svg, but there are problems with dark/light theme.

**Comment by elibroftw** [comment]
What was the problem exactly?

**Comment by Mitrichius** [comment]
Thanks for the idea! Changed to SVG icon.
