### ISSUE TITLE
Feature Request: Unlisted drafts

### ISSUE THREAD

**Issue by elibroftw** [Mitrichius/hugo-theme-anubis#124]
It would be great if there was an option to hide drafts from the index page if they were built. That way I could set `buildDrafts: true` for Hugo and `unlistedDrafts: true` for Anubis in the config file so that drafts can only be accessed with direct links and not through the home page.

Currently, I've come up with my own custom unlisted scheme. That is `/unlisted/test` with `draft: false`. When I'm ready to list the post, I move the file under `/posts` and add `aliases: ["unlisted/test"]` for backwards compatibility.

Not sure if this is a feature worth pursuing for you as I've come up with my own hackish work around.

**Comment by Mitrichius** [comment]
Is the use of drafts really necessary? Would you be okay with a `hidden = true` page parameter solution?

**Comment by elibroftw** [comment]
Either or to be honest. I just wanted a way for the post to be unlisted.

**Comment by Mitrichius** [comment]
Done! 
Add `hidden: true` to post front matter. Post also is not available in RSS feed and by search engines. 
As example: https://hugo-theme-anubis.netlify.app/post/hidden-post/

**Comment by elibroftw** [comment]
Oh and btw, can you document the rss page on the readme? It took me too long to find the first time. I think you should allow rss as a social icon. Right now what I've done is use rss as a custom social icon with a custom rss svg icon. 

See https://elibroftw.github.io/ for how it looks.
Source code
https://github.com/elibroftw/elibroftw.github.io

**Comment by Mitrichius** [comment]
Good idea. Created issue for this #128
