### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by thepaulmacca** [Mitrichius/hugo-theme-anubis#131]
Thanks for the work you've done on this theme, really like it! 👍🏻

Can you advise how I can add a favicon to my site please?

Thanks

**Comment by Mitrichius** [comment]
Hi! Thanks for kind words :)

Just add `favicon.png` and `favicon.ico` to `static` directory of your blog (sources, not build directory).

Or you can rewrite `favicons.html` partial and add any favicons you needed (same - to `static` directory). Check [this blog](https://github.com/iakunin/blog/blob/main/layouts/partials/favicons.html) sources as example

**Comment by thepaulmacca** [comment]
Ah ok thanks I'll give that a go, still learning Hugo a bit at the moment. Appreciate the reply!
