### ISSUE TITLE
PR #129 Breaks Attributes

### ISSUE THREAD

**Issue by W0CHP** [Mitrichius/hugo-theme-anubis#135]
Since PR #129, inline heading attributes no longer work (e.g. class, style, etc.).

Example...

Here's my actual markdown:

```
## Installing `W0CHP-PiStar-Dash` {style="background: #1E3C3C; padding:10px 0 10px 10px;"}
```

How it renders:

![Screenshot 2022-01-23 6 27 02 AM](https://user-images.githubusercontent.com/226376/150678364-7fe4928c-2f32-4651-bc23-f7c349341df1.png)

Yay! `\o/`

However, once I place `render-heading.html` into `_markup`, I lose all attributes:

![Screenshot 2022-01-23 6 14 01 AM](https://user-images.githubusercontent.com/226376/150678132-0bc03509-88f0-4680-a4df-3e74dbc6111d.png)

In `render-heading.html`, I did try adding `{{ .Attributes }}` within the `<h{{ .Level }}...`, hoping that I could fix it and submit a PR, but to no avail. :-( I'm not quite sure how to fix this issue.

**Comment by Mitrichius** [comment]
Sorry for that, didn't know about this feature at all.  
Should be fixed now.

**Comment by W0CHP** [comment]
> Sorry for that, didn't know about this feature at all. Should be fixed now.

Oh gosh, no worries mate! Thank you for the fix. :-)
