### ISSUE TITLE
rssAsSocialIcon should use baseName

### ISSUE THREAD

**Issue by nickgerace** [Mitrichius/hugo-theme-anubis#136]
I love this theme and thanks for the work on it! I noticed `rssAsSocialIcon` was recently added: https://github.com/Mitrichius/hugo-theme-anubis/commit/47a0734cce7eb13c1b5779818670b582fe9ee53d

Great feature! The only thing that makes it not work for me is that it does not use the `baseName`.
I believe it should use that value if it exists for backwards compatibility reasons (e.g. the site's RSS feed was `/feed.xml` before using this theme).

```yaml
outputFormats:
  RSS:
    baseName: "feed"
```

**Comment by Mitrichius** [comment]
Thanks for providing info about this issue!  
Should be fixed now.

**Comment by nickgerace** [comment]
Thanks! I think it works :)
