### ISSUE TITLE
Disabling Comments on Static Pages?

### ISSUE THREAD

**Issue by SkilledAlpaca** [Mitrichius/hugo-theme-anubis#147]
Is there a param to disable Disqus or any of the commenting solutions on a page per page basis?

**Comment by Mitrichius** [comment]
Right now it's not possible.  
Do you need a param to hide comments for all static pages or per page?

**Comment by SkilledAlpaca** [comment]
I am looking to just disable it on a per-page basis.

**Comment by KyleKun** [comment]
Up, this feature would be really nice.

**Comment by Mitrichius** [comment]
Add `disableComments: true` to post front matter.

**Comment by baeknab** [comment]
> Add `disableComments: true` to post front matter.

hi. Thanks for making the theme. thank you But it doesn't work in my environment.

**Comment by Mitrichius** [comment]
@dqlog if this is still actual, please reopen it
