### ISSUE TITLE
Inline preformatted text in dark mode has intense white background

### ISSUE THREAD

**Issue by jship** [Mitrichius/hugo-theme-anubis#148]
Thanks for the excellent theme! I noticed when using the dark theme, inline preformatted text (via single backticks) has a pretty intense white background, but code blocks of `text` type do not. Is there an easy way to configure the inline preformatted text's colors to match the code block colors?

![image](https://user-images.githubusercontent.com/1744045/162594200-a9dd3954-5a9b-42d5-a8c5-d075d4a15f54.png)

**Comment by Mitrichius** [comment]
Thanks for pointing this out, should be fixed now

**Comment by jship** [comment]
Looks great - thank you!
