### ISSUE TITLE
exampleSite menu in about page

### ISSUE THREAD

**Issue by tpennycook** [Mitrichius/hugo-theme-anubis#151]
The example site has a site wide menu (containing About Tags and Archive) and in the about page there is a second menu containing About and Subpage. The Subpage menu item appears to just link back to the about page. Should the example show a different page when one clicks on the Subpage menu item? I see there is an about-subpage.md file in content..

I wonder if this would help people looking to rapidly adapt your template for their use case? In my case I am looking to adapt the second layer menu example for a section with a number of different pages.

**Comment by Mitrichius** [comment]
There was a bug about generated urls in page menu, fixed it. Also updated example sites to improve clarity.
Thank you!

**Comment by tpennycook** [comment]
Thanks!
