### ISSUE TITLE
Changing the language doesn't change the lang="en-us" tag

### ISSUE THREAD

**Issue by deepakness** [Mitrichius/hugo-theme-anubis#155]
I am not very sure about how it works, but after changing the language to PL still has `<html lang="en-us">`  in the source code. Is there any way to fix that? Thanks.

**Comment by Mitrichius** [comment]
Yeah, I didn't take that into account. Now you can specify the locale parameter in the config params section for each language, see example https://github.com/Mitrichius/hugo-theme-anubis/blob/master/exampleSiteMultilingual/config.toml

**Comment by deepakness** [comment]
Yes, it works.
