### ISSUE TITLE
Change light/dark mode button to a social icon

### ISSUE THREAD

**Issue by Justinzobel** [Mitrichius/hugo-theme-anubis#167]
I'd love to see it moved into the header as an icon like below with it showing the option you can switch to.

![image](https://user-images.githubusercontent.com/1370117/198875727-6b5a4f9a-8031-416f-9fcd-916780c6bd3b.png)

**Comment by alxndr42** [comment]
I kind of like the switcher at the bottom of the page (maybe make it configurable, unless that would get too complicated), but these icons are neat.

**Comment by ihsanpraditya** [comment]
If it means switch dark-light button position to social icons, I make it here in my [repo](https://github.com/ihsanpraditya/anubis-custom), I had archived because I look that the true way is forking this repo than making a clone one. I use the theme in my [site](https://ihsanpraditya.web.id/) too.
