### ISSUE TITLE
Using baseURL breaks down website in production

### ISSUE THREAD

**Issue by eviscerat** [Mitrichius/hugo-theme-anubis#174]
I host my blog on aws s3. I had to comment `baseURL` in config.toml because the js and css paths would be broken in production.
The paths would be generated like this if I leave baseURL:
`<a class="u-url" href="https://example.com/posts/post/">`

Without base URL the paths are generated in a relative way - THIS is working:
`<a class="u-url" href="/posts/post/">`

Please come with a more robust solution

**Comment by W0CHP** [comment]
> Please come with a more robust solution

LMFAO demanding!  Submit a bloody PR!

**Comment by eviscerat** [comment]
> > Please come with a more robust solution
> 
> LMFAO demanding! Submit a bloody PR!

Submit deez nuts

**Comment by Mitrichius** [comment]
@eviscerat Can you show an example of this behaviour?  
And what's the main problem - links to JS and CSS / links to posts / all of them?

**Comment by eviscerat** [comment]
Ok, just re-tested this on a fresh copy of your repo using the exampleWebsite provided, re-uploaded to s3, no changes to config, the website renders paths correctly. Apologies, I ll close this issue.
