### ISSUE TITLE
Is there any possibility to delete a dividing lines? 

### ISSUE THREAD

**Issue by konstvatruba** [Mitrichius/hugo-theme-anubis#179]
Tried to search everything that looks like <hr> or <div>, but didn't find the one I need. The theme is perfect, but the lines are really not that useful. 

Cheers!

**Comment by Mitrichius** [comment]
Hi!

Create or update file `assets/css/custom.css`, add to it:
```
article:not(:last-of-type) {
    border: none;
}

.common-header {
    border: none;
}

.common-footer {
    border: none;
}
```
