### ISSUE TITLE
Hidden posts still appear in the sitemap

### ISSUE THREAD

**Issue by RoneoOrg** [Mitrichius/hugo-theme-anubis#189]
Hi there,

hidden posts are still appearing at least in the sitemap, see here for example: https://hugo-theme-anubis.netlify.app/en/sitemap.xml

I've been working on this feature, with the theme Papermod, see this post for an overview: https://roneo.org/en/hugo-hidden-posts/

**Comment by Mitrichius** [comment]
Thank you, fixed!
