### ISSUE TITLE
Inline preformatted text in light mode has intense dark background

### ISSUE THREAD

**Issue by antifuchs** [Mitrichius/hugo-theme-anubis#193]
I'm working on publishing a site with the light theme and now I have the exact inverse problem as #148: inline preformatted text is a very intense dark background that looks just as jarring as the one in the same bug about the dark mode issue:

<img width="664" alt="image" src="https://github.com/Mitrichius/hugo-theme-anubis/assets/11864/9f86be1e-8986-4130-a83a-6529f00dfe7b">

Looking at https://github.com/Mitrichius/hugo-theme-anubis/commit/c4665390d2a33a31b2b6ad1a7fd7cd9a6f9c1795, I think it might be enough to revert the changes to assets/css/light.css and restoring the light background?

**Comment by Mitrichius** [comment]
Colors are reverted for light theme, thanks
