### ISSUE TITLE
Question: Markdown in title

### ISSUE THREAD

**Issue by talbii** [Mitrichius/hugo-theme-anubis#198]
Hey there! I've been using the theme for a while, and one thing that bothers me is that titles cannot have Markdown in them. For example:

```
---
title: "Hello *world*"
...
---
```

would render as a post with the title being `Hello *world*`. 

Is there away to use some basic formatting in the title? Specifically, I am interested in inserting `monospace text` in the title.

Thanks! :)

**Comment by Mitrichius** [comment]
Added support for this, should work now

**Comment by talbii** [comment]
thanks! I can confirm it is working :)
