### ISSUE TITLE
Surface ReadingTime in default template

### ISSUE THREAD

**Issue by williewillus** [Mitrichius/hugo-theme-anubis#207]
As title, just would be nice to have this https://gohugo.io/methods/page/readingtime/ show up above the Table of Contents, so I don't have to patch the theme.

**Comment by Mitrichius** [comment]
Hi, 
I don't like realization of reading time in Hugo with i18n — need to support all kind of forms (minute/minutes/other forms in different languages). It's hard to make it universally correct.

As a easiest workaround, you can copy `themes/anubis/layouts/partials/toc.html `file to `layouts/partials/toc.html` and add reading time to it.
