### ISSUE TITLE
Where is the RSS?

### ISSUE THREAD

**Issue by bbohling** [Mitrichius/hugo-theme-anubis#28]
I'm sure I'm going something stupid, but I can't find the RSS feed. In my production site it states it is at: `https://www.brandonbohling.com/rss/`, but it is not. Looking into the `layouts/_default` I see the `rss.xml` template. 

What am I missing?

**Comment by bbohling** [comment]
Well I found it at: `https://www.brandonbohling.com/index.xml` finally, but still all the pieces don't line up. Could you update the theme or would you prefer a PR?

**Comment by Mitrichius** [comment]
@bbohling Sorry for this, now link is correct

**Comment by bbohling** [comment]
Thanks for the speedy fix and excellent theme!
