### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by shalastra** [Mitrichius/hugo-theme-anubis#30]
Hey, 
you've create a great theme. 
I have one question though - I'm trying to setup Google Analytics in the config, I pasted the the code, starting with `UA-<number>`. Unfortunately, it doesn't work. Should I do anything else?

**Comment by Mitrichius** [comment]
Hi @shalastra !
I don't think so. Theme uses Hugo internal template for GA, so your id in config should be enough. 
Maybe some syntax mistake? Check this https://gohugo.io/templates/internal/#configure-google-analytics
And check your GA id in builded html pages. If page contains id, then problem with GA settings on GA side.
If it doesn't help, provide your config please.

**Comment by shalastra** [comment]
Hi,
After a short investigation I think the issue is that the HUGO_ENV is not set as production on my github page.

**Comment by Mitrichius** [comment]
Sorry, totally forgot about Hugo environments.  

You should build with environment setting, e.g.:
`HUGO_ENV=production hugo --minify`
and deploy result on GH pages

**Comment by shalastra** [comment]
Thanks, now the Google Analytics is added.
