### ISSUE TITLE
Add `_index.md` Content to the Homepage

### ISSUE THREAD

**Issue by TheDocTrier** [Mitrichius/hugo-theme-anubis#31]
It would be nice if Anubis included the content from _index.md at the top of the homepage similar to https://gohugo.io/templates/homepage/#add-content-and-front-matter-to-the-homepage .

**Comment by Mitrichius** [comment]
@TheDocTrier thanks, done it. Also add support of _index.md for posts, tags and categories pages

**Comment by TheDocTrier** [comment]
@Mitrichius Awesome, thank you!
