### ISSUE TITLE
Error on building

### ISSUE THREAD

**Issue by huzaifahj** [Mitrichius/hugo-theme-anubis#33]
`
Building sites … ERROR 2020/05/15 12:23:32 render of "section" failed: execute of template failed: template: _default/list.html:15:15: executing "main" at <partial "articleInfo...>: error calling partial: "/home/huzaifahj29/quickstart/themes/anubis/layouts/partials/articleInfoFull.html:3:44": execute of template failed: template: partials/articleInfoFull.html:3:44: executing "partials/articleInfoFull.html" at <.Params.date.format>: can't evaluate field format in type interface {}
`

I'm getting this. I've just set up a quickstart Hugo project, and activated Anubis as the theme in the .yaml. I've done nothing else so I'm unsure what happened

**Comment by Mitrichius** [comment]
Hi!
I can't reproduce this error on quickstart project.
Could you please provide your hugo version, config.yaml and your post metadata (https://gohugo.io/content-management/front-matter/), if you're already added some content?
