### ISSUE TITLE
Custom Css

### ISSUE THREAD

**Issue by matheusmassa** [Mitrichius/hugo-theme-anubis#35]
I'm trying to activate my custom css but i have this error:

`Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:5:11: executing "head" at <partial "head.html" .>: error calling partial: "D:\Projetos\teste-1\themes\anubis\layouts\partials\head.html:19:14": execute of template failed: template: partials/head.html:19:14: executing "partials/head.html" at <.Site.Params.customCSS>: range can't iterate over css/my.css`

My config.toml:
`[params]
   author = "Dmitry Kolosov"
   description = "Anubis is a simple minimalist theme for Hugo blog engine."
   customCSS = "css/my.css"`

I tried to save my css files in different ways, such:
```
root
  | - css
  |   | - my.css

```
or

```
root
| - static
|  | - css
|  |  | - my.css
```

hugo version: Hugo Static Site Generator v0.71.1-A301F6B2 windows/amd64 BuildDate: 2020-05-25T09:12:07Z

**Comment by Mitrichius** [comment]
customCss in config is array, so you should enable it like this: 
`customCSS = ["css/my.css"]`
Also your second try is correct, it should be in static directory (I'll update readme)

**Comment by matheusmassa** [comment]
It worked!

Thks.
