### ISSUE TITLE
Deploy problem

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [Mitrichius/hugo-theme-anubis#36]
Hi all, I have installed theme and in locally if I launch 
```
hugo server
```

It works all fine. 
Now I would like to deploy my site with github following the hugo documentation.
this is my deploy script:

```
#!/bin/bash

echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"

# Build the project.
hugo -t anubis # if using a theme, replace with `hugo -t hugo-nuo`

# Go To Public folder
cd public
# Add changes to git.
git add .

# Commit changes.
msg="rebuilding site `date`"
if [ $# -eq 1 ]
  then msg="$1"
fi
git commit -m "$msg"

# Push source and build repos.
git push origin master

# Come Back up to the Project Root
cd ..
```

homepage works fine but pages videos and post don't have css style.
Do you know why?

this is the URL:
[My site](https://alessandrominoccheri.github.io/)

Thanks

**Comment by AlessandroMinoccheri** [comment]
I have solved adding custom CSS, but I think that is not a good solution.

**Comment by Mitrichius** [comment]
Hi @AlessandroMinoccheri 
Please fill `baseUrl` param in site config — without it, absolute links to css and other things become relative.

**Comment by AlessandroMinoccheri** [comment]
ok, thanks!
