### ISSUE TITLE
Missing _internal file

### ISSUE THREAD

**Issue by angepili** [Mitrichius/hugo-theme-anubis#37]
Hi! I have downloaded now for the first time, after launching hugo server, the terminal return this error:
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:5:11: executing "head" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:41:17: executing "_internal/opengraph.html" at <index $siteSeries $name>: error calling index: index of untyped nil

**Comment by Mitrichius** [comment]
Hi!
It's because `series` taxonomy used somewhere in the posts, but not enabled in config.  
Just add it to taxonomy section in config or don't use it in posts. 

If you used files from `exampleSite`, there was a mistake with series (it shouldn't be here), which I fixed now.

**Comment by angepili** [comment]
Ok it's working, thanks!
