### ISSUE TITLE
Make google font optional

### ISSUE THREAD

**Issue by forty** [Mitrichius/hugo-theme-anubis#52]
Hello, 

I'm using your great theme, thanks! 

the only modification I have left now is that I drop the Google font import (I'm sure this specific font is great for some reasons, but I'm not very comfortable of having google tracking everything on the web, my website included). It's not a lot, but I still need to rebase it regularly :)

Do you think a theme parameter could be added to make it optional (like `noGoogleFont`, which would be `false` by default so people would still get it by default)

I'm happy to try to make the PR if you are interested.

**Comment by Mitrichius** [comment]
Removing google font was in my plans too, so thanks for push to action :)
I already did it - just update.

**Comment by forty** [comment]
This is great, thanks!
