### ISSUE TITLE
Add Margin to Bottom of Theme Switcher

### ISSUE THREAD

**Issue by TheDocTrier** [Mitrichius/hugo-theme-anubis#61]
When viewing a site on mobile devices, the theme switcher will move below the copyright div. However, the theme switcher has no margin-bottom and so touches the bottom of the screen. I think it would look better if there was 1em of margin (the same margin as is on the right of the theme switcher) below it. I'll make a small pull request for the proposed change.

Before:
![image](https://user-images.githubusercontent.com/9048525/92290886-bf639380-eeca-11ea-8424-719fe6f78c3a.png)

After:
![image](https://user-images.githubusercontent.com/9048525/92290901-d4402700-eeca-11ea-96dd-b91d85500448.png)

**Comment by Mitrichius** [comment]
Thanks! It's really better.
