### ISSUE TITLE
Issue with images when baseUrl has a path

### ISSUE THREAD

**Issue by ashfaqfarooqui** [Mitrichius/hugo-theme-anubis#64]
I have set my baseUrl to be: `https:example.com/test`
This works fine for posts. But for the images under in any post, it still looks for the static repository without the "test".
For example, if I have an image file image.jpg located in the static repository, I can access it using `example.com/test/image.jpg`. But in the post, the URL is expanded as: `example.com/test/image.jpg`

Am I missing some setting?

**Comment by Mitrichius** [comment]
Hi!

Try using `canonifyURLs: true` in the config file. I did a test, it works.
Ref: https://discourse.gohugo.io/t/solved-generate-wrong-image-relative-url/11726

If this doesn't help, add an example of how you add images to the post.
Also,  links to the image are the same in your comment.

**Comment by ashfaqfarooqui** [comment]
That fixed it, thanks.
