### ISSUE TITLE
Unable to transform style.css, resource not found in file cache

### ISSUE THREAD

**Issue by TheDocTrier** [Mitrichius/hugo-theme-anubis#66]
Commit db7e6254fa6105ae477a9b0bc3ee268d0e20fd17 causes Hugo to error out with

```
Total in 37 ms
Error: Error building site: TOCSS: failed to transform "css/style.css" (text/css): resource "css/css/main.css_b5616ad8043936b93a403785b10b2b88" not found in file cache
```

printed to the console. Rolling back to the previous commit, 9e524ff754b0abfb2887f448a52c2c2cf3bc6f47, resolves the issue. In case it's helpful, the repository I'm using Anubis in is https://github.com/TheDocTrier/disjoint-union.

Side note: I saw that my previous issue #63 was just fixed (thank you!) in the latest merge, so I decided to try it out.

**Comment by Mitrichius** [comment]
I can't reproduce it with your repo and updated theme on my environment.
What is your environment - OS and Hugo version?

**Comment by forty** [comment]
Cannot repro either (Debian Bullseye, Hugo v0.75.1). Seem fine on Netlify too.

**Comment by TheDocTrier** [comment]
Sorry, I just realized that I was using an outdated ppa for Hugo. After updating to the latest copy on GitHub there are no errors.

**Comment by meme-lord** [comment]
I'm using the latest version of Hugo and I'm getting this issue.
```
user@debian:~# hugo version
Hugo Static Site Generator v0.77.0-EF290125 linux/amd64 BuildDate: 2020-10-30T10:14:31Z
user@debian:~# hugo new site test
user@debian:~# cd test
user@debian:~/test# git init
Initialized empty Git repository in /root/test/.git/
user@debian:~/test# git submodule add https://github.com/mitrichius/hugo-theme-anubis.git themes/anubis
user@debian:~/test# mv config.toml config.yaml
user@debian:~/test# nano config.yaml # put the config from the README in
user@debian:~/test# hugo serve
Start building sites … 
Built in 15 ms
Error: Error building site: TOCSS: failed to transform "css/style.css" (text/css): resource "css/css/main.css_b5616ad8043936b93a403785b10b2b88" not found in file cache
```

**Comment by meme-lord** [comment]
Nevermind I found the issue, I wasn't using the "Hugo extended" which seems to be required.

**Comment by forty** [comment]
Good catch. If the only reason why the extended version is required is this ToCSS filter, we could consider removing it, it's not that useful: I originally planned to use it for minification as the documentation says it might be more efficient than the generic minifier, but in my tests it turned out that the generic one does better here so I ended up using that. I let the ToCSS because it does formating for dev mode, and can catch CSS syntax error, but I don't know if it's worth the bugs people will open when it doesn't work with their hugo binary

**Comment by Mitrichius** [comment]
@forty Thanks for the explanation.
I decided to remove it e9ee82e
