### ISSUE TITLE
Custom css still uses epoch instead of hash

### ISSUE THREAD

**Issue by TheDocTrier** [Mitrichius/hugo-theme-anubis#69]
See the lines:

https://github.com/Mitrichius/hugo-theme-anubis/blob/4c1ba11756d1a96d92e42b99bacdbdc8cbdc0f49/layouts/partials/head.html#L25-L27

I'm not sure how much work is required to switch it to something like the preceding lines:

https://github.com/Mitrichius/hugo-theme-anubis/blob/4c1ba11756d1a96d92e42b99bacdbdc8cbdc0f49/layouts/partials/head.html#L17-L23

**Comment by Mitrichius** [comment]
Thank you for pointing out this issue, fixed in e9ee82e. Now all CSS and JS files are fingerprinted and minified (for production env).
You must move your custom CSS and JS files to `assets` directory to make it work.
