### ISSUE TITLE
Adding a site index.md breaks menu links

### ISSUE THREAD

**Issue by MarkusG** [Mitrichius/hugo-theme-anubis#71]
Creating a file `content/index.md` replaces the landing page's default listing of posts as expected, but causes my "Posts" link in the menu to 404. My directory structure is as follows:
```
├── content
│   ├── index.md
│   └── posts
│       ├── post1.md
│       ├── post2.md
│       ├── post3.md
│       └── post4.md
```

I'm not sure if this is an error in my usage or an error in the theme. Is there another preferred way to set other content on the landing page?

**Comment by Mitrichius** [comment]
Hi!
This is strange behaviour indeed, index.md affects not only "Posts" page, but also other single pages like "About" in the site example.  
For now I don't have a proper solution. I'll try to understand and fix it within next few days.

As a workaround, you may create file `layouts/index.html` with content:
```
{{ define "main" }}
    Index content inside default layout
{{ end }}
```
It will change content of the index page without affecting other pages.

**Comment by Mitrichius** [comment]
So, I've checked this case on other themes (e.g. ananke) and behaviour looks the same (pages are 404 or disappeared from menu at all).

Where did you find such usage of index.md? 
I found only [this page](https://gohugo.io/content-management/page-bundles/). In other places there is only _index.md mentions.

**Comment by MarkusG** [comment]
I came up with it myself. I wanted to have some "About" information on the landing page instead of the list of posts, so I figured creating an `index.md` in the `content/` directory would do that for me. Perhaps I'm going about it in the totally wrong way?

**Comment by Mitrichius** [comment]
Try create `layouts/index.html` as I said in my first comment.

**Comment by MarkusG** [comment]
Yeah, that worked like a charm. Thanks!
