### ISSUE TITLE
What is the current version when installing?

### ISSUE THREAD

**Issue by antois** [Mitrichius/hugo-theme-anubis#73]
Hello Dmitry,

Thanks for your theme, I really like it. I was thinking of adopting it for my Hugo blog and I am a bit confused by the versioning. I saw you mentioned forthcoming v.1.2 several times and I also saw some updates after v.1.1 was released. So if I want to install the latest version of the theme, should I follow the stated installation procedure or should I do something else in order to stay up-to-date?

Thanks in advance.

PS: I also had a few  basic questions on how to tweak this theme (bold & larger size site title and get rid of top and bottom lines), where could I ask them?

All the best,
A

**Comment by Mitrichius** [comment]
Hello!

I don't follow strict versioning here at Anubis. No semver, no patch versions, etc. Versions here more like a milestones.  
So if you want be always up-to-date with the latest version, just add theme as submodule and regularly update:  
`git submodule update --remote`

But if you need stick to specific version, I can use semver or just do more frequent releases/versions.

About the tweaking: you can add your css file and override css styles from theme. 
For example, create assets/css/custom.css file and add:
```
.common-header {
    border-bottom: none;
}

.common-footer {
    border-top: none;
}

.site-title {
    font-weight: bold;
    font-size: 1.5em;
}
```
After that, update config: add customCSS to params section (see full example in Readme):
```
  customCSS:
    - css/custom.css
```

And finally, rebuild website.


You can reach me:
- here :) Don't hesitate to open an issue for a simple question;
- by email: mitrichius@gmail.com
- in Telegram: @mitrichius

**Comment by antois** [comment]
Thank you so much for the thoughtful reply! I will try to implement this. 

Additionally, may I report this slight misalignment of the light/dark theme switch with the right border of the blog? Alternatively, do you know how I could fix it myself?

![Screenshot 2020-11-25 at 23 04 04](https://user-images.githubusercontent.com/29061826/100286224-7da33000-2f83-11eb-8e3a-0db89c777cc8.jpg)

Thanks!

**Comment by Mitrichius** [comment]
Yeah, thanks, fixed it.
