### ISSUE TITLE
Webmention/Indieweb support

### ISSUE THREAD

**Issue by ambroisie** [Mitrichius/hugo-theme-anubis#75]
It would be great if there was support for webmentions (e.g: https://webmention.io/) and the larger indieweb movement (e.g: https://indiewebify.me)

**Comment by Ambroisie** [comment]
On my personal blog, I have modified the footer template to add various `rel=me` links for example (a `footer-extra` similar to `head-extra` would be great for this by the way).

**Comment by Ambroisie** [comment]
[Here's the IndieWeb wiki's page on Hugo](https://indieweb.org/Hugo).

Of note is this [guide](https://www.amitgawande.com/2018/02/10/204300.html) for the first few steps of indiewebification.

**Comment by Mitrichius** [comment]
Add header-extra and footer-extra. 
Also add support for webmentions via config:
```
params:
  webmentions:
    login: hugo-theme-anubis
    pingback: true
```

And finally add a note about "rel=me" to #6

**Comment by Ambroisie** [comment]
I think some way to display comments via ping back is possible during the build process by using the API. I found this [thread](https://discourse.gohugo.io/t/anyone-for-webmention/10411/6) which hinted at a possible solution.

**Comment by Ambroisie** [comment]
And of course, there's the missing support for microformats which I haven't seen mentionned yet.

Thank you for your work on this theme, I really like it!

**Comment by Mitrichius** [comment]
Added microformats support.
Pingback: I will check thread later.

**Comment by NilsKempen** [comment]
Maybe the config should not ask for a https://webmention.io/ login but for a webmention receive URL to support other webmention services then webmention.io . I think this could be done by changing the config variable from login to url and load the complete url in head.html. I have successfully tested it here:
https://github.com/NilsKempen/hugo-theme-anubis/commit/581827ee8ea87f5fd50620e627824370dfadb7ce
