### ISSUE TITLE
list.html always shows all content

### ISSUE THREAD

**Issue by vringar** [Mitrichius/hugo-theme-anubis#90]
When using list.html it always displays all articles no matter which section you are on.
So if you have the following content directory:
```
content
└── posts
|   └── series-a
|   |   ├── first-post.md  
|   |   ├── second-post.md
|   |   └── _index.md  
|   └── series-b
|       ├── firstpost.md  
|       ├── secondpost.md  
|       └── _index.md  
└── _index.md
``` 
All four lists `example.com/`, `example.com/posts`, `example.com/posts/series-a` and `example.com/posts/series-b` will display the same four blog posts.

However I would expect that `example.com/posts/series-a` only shows posts for Series A and `example.com/posts/series-b` only shows posts for Series B.

This can be done by changing 
https://github.com/Mitrichius/hugo-theme-anubis/blob/a6b89f92e27945830ff48f7e46bd3e53b869ccad/layouts/_default/list.html#L8-L9

to `.Pages` instead of `site.RegularPages`

Would you accept a PR making this change or is this against the design of your theme?

**Comment by Mitrichius** [comment]
Thank you!
