### ISSUE TITLE
Support for language switch on the specific page/article

### ISSUE THREAD

**Issue by cuichacha** [Mitrichius/hugo-theme-anubis#92]
Hello Dmitry, sorry to bother you. 
Thank you for providing this wonderful theme.  
Recently I tried the Anubis theme and it's pretty neat.
I wonder if the Anubis theme can support language switch for the specific single article.
Currently I've realized the switch for the entire blog. 
I have tried but failed to switch the single page. 
For each article, I have two versions in two languages. They have the same file name but are stored in different path.
I am not familiar with front end technology and don't know to how to change the path through menu on the page. 
I am not sure whether the Hugo config can support this feature or I need to modify the theme, which I tried but failed.
Thank you again for inventing this excellent theme. 
Really want to visit Russia some day since I am not very far from this great country.

**Comment by Mitrichius** [comment]
Hello!  
According to documentation, it's possible, but need some development from my side (especially interface) https://gohugo.io/content-management/multilingual/#reference-the-translated-content  
I plan to do it next week

**Comment by cuichacha** [comment]
Thank you Dmitry! Can't wait to try this feature which is very necessary to me. Really love your theme!

**Comment by Mitrichius** [comment]
Ready!
You can see the result on release page: https://github.com/Mitrichius/hugo-theme-anubis/releases/tag/1.2.1

However, due to Hugo engine, link to translated page switches the language for full site. Maybe there is a better solution, but I don't found it

**Comment by cuichacha** [comment]
Thank you sooooo much!
This feature is absolutely great for multilingual people to practice their language skills and there are only a few Hugo themes (may be 3 or 4) that provide this function. 
You really should put this feature on Hugo theme gallery page. (https://themes.gohugo.io/themes/hugo-theme-anubis/)
I strongly believe that many people will love it! 
Thank you again!
