### ISSUE TITLE
Pagination does not work in Chinese

### ISSUE THREAD

**Issue by cuichacha** [Mitrichius/hugo-theme-anubis#94]
Pagination works in English but not works in Chinese. 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/12711401/126036828-71bc0439-ba66-4e19-9b73-1d06ea61d0b4.png">

<img width="850" alt="image" src="https://user-images.githubusercontent.com/12711401/126036835-da79de19-7523-4a26-afa5-1bdddc889b4e.png">

Here is the TOML config

<img width="442" alt="image" src="https://user-images.githubusercontent.com/12711401/126036853-3f78f7a2-91c7-4d3b-8d99-b97195048914.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/12711401/126036869-5248ecff-efd9-49fb-ba7d-62028f6bb615.png">

**Comment by Mitrichius** [comment]
There is no translation file for this language.  
Translation file directory: `themes/anubis/i18n`

You need to add a file with your language code to this directory and translate messages. After it you can make PR or just add a comment here with the attached file. I will add it to the theme.

**Comment by cuichacha** [comment]
Oh, this is the reason. Thank you!!
[zh-cn.yaml.zip](https://github.com/Mitrichius/hugo-theme-anubis/files/6838398/zh-cn.yaml.zip)

**Comment by Mitrichius** [comment]
Added it to the theme. Thanks!
