### ISSUE TITLE
Broken pagination links (post page) on multilingual site

### ISSUE THREAD

**Issue by iakunin** [Mitrichius/hugo-theme-anubis#95]
Hi, @Mitrichius! Many thanks for such a great hugo-theme!

I've found a bug with pagination links on post page (multilingual site).

### Steps to reproduce
1. Go to https://iakunin.dev/ru/post/rich-content/
2. Scroll down to the bottom of the page
3. Click on the next page link (see [the screenshot](https://user-images.githubusercontent.com/10430347/130653512-b5dc51c4-cfc6-4124-9d93-1eca6a8f56ff.png))
4. And we've got "404 Page not found" error

I have some thoughts about the root cause of this bug. And here is [my PR](https://github.com/Mitrichius/hugo-theme-anubis/pull/96).

**Comment by Mitrichius** [comment]
Fixed by merge PR. Thank you!
