### ISSUE TITLE
Configure the width of posts' text

### ISSUE THREAD

**Issue by plagov** [Mitrichius/hugo-theme-anubis#97]
Hi!

First of all, thanks for the theme! I'm using it for my personal blog.

Is it possible to configure the width of the text block in posts? I found it a bit narrow. Even on a 13" laptop, there's still space available on both sides. When having just a text in the post, then it's fine. But when entering a code block, then there's a horizontal scroll bar, which is not very convenient to use while reading the code.

**Comment by Mitrichius** [comment]
Hi!
You could do it via custom css and changing max-width for container.

Example of custom css file:
```
.container {
    max-width: 50em;
}
```

Consider this changes width for all blocks including header and footer. 
If this solution good for you?

**Comment by plagov** [comment]
@Mitrichius thanks for the help! That solved my request!
